### ISSUE TITLE
Install  hi.pl on web server

### ISSUE THREAD

**Issue by philiprbrenan** [ricksnp/symmetrical-invention#4]
Install the hi.pl program as:

    /usr/lib/cgi-bin/hi.pl

Set permissions with:

    chmod ugo+x hi.pl

Then in a browser:

    ipaddress/cgi-bin/hi.pl

Please let me know if it does not work?l

**Comment by ricksnp** [comment]
Working on this!

**Comment by ricksnp** [comment]
Success - I see "Hello World"!
